name: tugela
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.2.0+14

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  encrypt: 5.0.1
  equatable: ^2.0.5
  file_selector: ^1.0.3
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_messaging: ^15.1.2
  firebase_remote_config: ^5.1.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  local_auth: ^2.2.0
  mime: ^1.0.5
  package_info_plus: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  phosphor_flutter: ^2.1.0
  provider: ^6.1.2
  recase: ^4.1.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app-icon.png"
  adaptive_icon_foreground: "assets/images/app-icon-foreground.png"
  adaptive_icon_background: "assets/images/app-icon-background.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
